Removed catching base64.binascii.Error
The error is not found and fails the CI/CD
I thought that the used library is
https://docs.python.org/3/library/base64.html#base64.b64decode

Removing to make the CI/CD pass again.

typing: commands[0]> mypy
src/itsdangerous/signer.py:233: error: Module has no attribute "binascii"
[attr-defined]
            except (BadData, base64.binascii.Error):
                             ^~~~~~~~~~~~~~~
src/itsdangerous/timed.py:116: error: Module has no attribute "binascii"
[attr-defined]
            except (BadData, base64.binascii.Error):
                             ^~~~~~~~~~~~~~~
Found 2 errors in 2 files (checked 8 source files)